B) Cofla vuelve de la comisaría exausto y por lo cansado que estaba se fue a dormir
Al otro día comienzan las clases del ciclo básico de la universidad ( porque cofla quiere ser programador y se inscribió en la facultad de ingenieria para estudiar desarrollo de software).
En su cuerso en total son 19 alumnos, pero surgió un problema que complicó un poco a la facultad: se rompió el sistema de registro de asistencias y durante los proximos 30 días no se podrán hacer registros de datos de ningun tipo, por ende las clases no podrán comenzar hasta que esto esté solucionado.

- Crear mini-sistema que nos permita registrar los alumnos que estan presentes (P) y ausentes (A) en clase.
- Pasados los 30 días, mostrar la situación final de todos los alumnos (Nro total de presentes y ausentes).
- Se puede tener un máximo de 10% de ausencias por semestre, si se tienen mas aclarar que está reprobado